import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class DeviceRegisterRequest(BaseModel):
    """Request to register a new device."""

    device_id: str = Field(
        ...,
        min_length=36,
        max_length=36,
        description="UUID generated by the client app",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )


class TokenResponse(BaseModel):
    """JWT token response."""

    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(default="bearer")
    expires_at: datetime = Field(..., description="Token expiration timestamp")


class DeviceInfo(BaseModel):
    """Device information."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    device_id: str
    created_at: datetime
    last_seen: datetime
