"""Initial schema

Revision ID: 20260224_000001
Revises:
Create Date: 2026-02-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20260224_000001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create devices table
    op.create_table(
        "devices",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "device_id",
            sa.String(36),
            unique=True,
            nullable=False,
            comment="UUID generated by client app",
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment="Future: link to user account",
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_devices_device_id", "devices", ["device_id"])

    # Create games table
    op.create_table(
        "games",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "client_id",
            sa.String(36),
            nullable=True,
            index=True,
            comment="WatermelonDB ID from client",
        ),
        sa.Column(
            "device_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("devices.id"),
            nullable=False,
            index=True,
        ),
        sa.Column("name", sa.String(100), nullable=True),
        sa.Column("target_score", sa.Integer(), default=100, nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "COMPLETED", name="gamestatus"),
            default="ACTIVE",
            nullable=False,
        ),
        sa.Column("winner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            default=False,
            index=True,
            comment="Soft delete flag for sync",
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            index=True,
            comment="For sync queries",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_games_client_id", "games", ["client_id"])
    op.create_index("ix_games_device_id", "games", ["device_id"])
    op.create_index("ix_games_is_deleted", "games", ["is_deleted"])
    op.create_index("ix_games_last_modified", "games", ["last_modified"])

    # Create game_players table
    op.create_table(
        "game_players",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "client_id",
            sa.String(36),
            nullable=True,
            index=True,
            comment="WatermelonDB ID from client",
        ),
        sa.Column(
            "game_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("games.id"),
            nullable=False,
            index=True,
        ),
        sa.Column("name", sa.String(50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False, comment="Display order"),
        sa.Column(
            "current_total",
            sa.Integer(),
            default=0,
            nullable=False,
            comment="Cached cumulative score",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            default=False,
            index=True,
            comment="Soft delete flag for sync",
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            index=True,
            comment="For sync queries",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_game_players_client_id", "game_players", ["client_id"])
    op.create_index("ix_game_players_game_id", "game_players", ["game_id"])
    op.create_index("ix_game_players_is_deleted", "game_players", ["is_deleted"])
    op.create_index("ix_game_players_last_modified", "game_players", ["last_modified"])

    # Add foreign key for winner_id now that game_players exists
    op.create_foreign_key(
        "fk_games_winner_id",
        "games",
        "game_players",
        ["winner_id"],
        ["id"],
    )

    # Create rounds table
    op.create_table(
        "rounds",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "client_id",
            sa.String(36),
            nullable=True,
            index=True,
            comment="WatermelonDB ID from client",
        ),
        sa.Column(
            "game_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("games.id"),
            nullable=False,
            index=True,
        ),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column(
            "caller_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("game_players.id"),
            nullable=True,
            comment="Player who called lookyswappy",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            default=False,
            index=True,
            comment="Soft delete flag for sync",
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            index=True,
            comment="For sync queries",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_rounds_client_id", "rounds", ["client_id"])
    op.create_index("ix_rounds_game_id", "rounds", ["game_id"])
    op.create_index("ix_rounds_is_deleted", "rounds", ["is_deleted"])
    op.create_index("ix_rounds_last_modified", "rounds", ["last_modified"])

    # Create scores table
    op.create_table(
        "scores",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "client_id",
            sa.String(36),
            nullable=True,
            index=True,
            comment="WatermelonDB ID from client",
        ),
        sa.Column(
            "round_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("rounds.id"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "player_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("game_players.id"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "raw_score", sa.Integer(), nullable=False, comment="Score before bonus"
        ),
        sa.Column(
            "bonus_applied", sa.Integer(), default=0, nullable=False, comment="-25 or 0"
        ),
        sa.Column(
            "final_score",
            sa.Integer(),
            nullable=False,
            comment="raw_score + bonus_applied",
        ),
        sa.Column(
            "total_after",
            sa.Integer(),
            nullable=False,
            comment="Running total after this round",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            default=False,
            index=True,
            comment="Soft delete flag for sync",
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            index=True,
            comment="For sync queries",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_scores_client_id", "scores", ["client_id"])
    op.create_index("ix_scores_round_id", "scores", ["round_id"])
    op.create_index("ix_scores_player_id", "scores", ["player_id"])
    op.create_index("ix_scores_is_deleted", "scores", ["is_deleted"])
    op.create_index("ix_scores_last_modified", "scores", ["last_modified"])


def downgrade() -> None:
    op.drop_table("scores")
    op.drop_table("rounds")
    op.drop_constraint("fk_games_winner_id", "games", type_="foreignkey")
    op.drop_table("game_players")
    op.drop_table("games")
    op.execute("DROP TYPE IF EXISTS gamestatus")
    op.drop_table("devices")
